name: tagging test

on:
  # push:
  #   branches:
  #     - "master"
  # schedule:
  #   - cron: "* */1 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     ref: ${{ github.event.head_commit.message }}
      - run: echo ${{ github.event.head_commit.message }}
      - name: Git Version Beta
        id: version
        if: ${{ !contains(github.event.head_commit.message, '[VERSIONING]') }}
        run: |
          git config --global user.email "opentrack.dev@gmail.com"
          git config --global user.name "opentrack"
          npm version prerelease --preid=beta -m "[VERSIONING] %s"
          git push origin
          git push origin $(git describe)
          echo "::set-output name=tag::$(git describe)"
      - name: Test
        run: echo ${{ steps.version.outputs.tag }}
