# This is a basic workflow to help you get started with Actions
name: tagging

# Controls when the action will run.
on:
  push:
  # Triggers the workflow on push or pull request events but only for the master branch
  # schedule:
  #   - cron: "*/15 * * * *"
  # paths-ignore:
  #   - "/**"
  # tags:
  #   - "v*.*.*-beta.*"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on

    # if: ${{ steps.version.outputs.tag != github.sha }}
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - name: commit log check
      #   id: describe
      #   run: echo "::set-output name=tag::$(git describe)"
      #   if: github.sha != ${{steps.describe.output.tag}}
      - uses: actions/checkout@v2
      - name: tag
        id: tag
        run: echo "::set-output name=tag::$(git describe)"
      - name: tag check
        if: ${{github.event.head_commit.message}} == ${{steps.tag.outputs.tag}}
        # if: ${{ startsWith(steps.tag.outputs.tag, 'v') }}
        run: "::error"
      - name: Git Version Beta
        id: version
        run: |
          git config --global user.email "opentrack.dev@gmail.com"
          git config --global user.name "opentrack"
          npm version prerelease --preid=beta
          git push origin
          git push origin $(git describe)
          echo "::set-output name=tag::$(git describe)"
      - name: Test
        run: echo ${{ steps.version.outputs.tag }}
