name: tagging

on:
  push:
  # schedule:
  #   - cron: "* */2 * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ startsWith(github.event.head_commit.message, '[VERSIONING]') }}"
      - name: tag check
        id: tag
        run: echo "::set-output name=versioning::${{ startsWith(github.event.head_commit.message, '[VERSIONING]') }}"
      - name: Git Version Beta
        id: version
        if: ${{ steps.tag.outputs.versioning }}
        run: |
          git config --global user.email "opentrack.dev@gmail.com"
          git config --global user.name "opentrack"
          npm version prerelease --preid=beta
          git push origin
          git push origin $(git describe)
          echo "::set-output name=tag::$(git describe)"
      - name: Test
        run: echo ${{ steps.version.outputs.tag }}
