name: tagging2

on:
  schedule:
    - cron: "* */2 * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Git Version Beta
        id: version
        if: ${{ !startsWith(github.event.head_commit.message, '[VERSIONING]') }}
        run: |
          git config --global user.email "opentrack.dev@gmail.com"
          git config --global user.name "opentrack"
          npm version prerelease --preid=beta -m "[VERSIONING] %s"
          git push origin
          git push origin $(git describe)
          echo "::set-output name=tag::$(git describe)"
      - name: Test
        run: echo ${{ steps.version.outputs.tag }}
